### ISSUE TITLE
Filters in 'orders' query

### ISSUE THREAD

**Issue by allesklar** [nukeproof/oanda_api#1]
Great gem. Thanks for your contribution.

I have this strategy that requires me to check whether there is an existing open order before placing a new one.

Using the REST API, is it possible to check that, for example, there is a pending buy limit order for EUR-USD at 1.0650 ??

I have gone through the whole OANDA documentation and can't figure this out. Furthermore, their tech support don't know and told me to contact their api email address but they won't answer my query.

Using their testing console suggests it's possible. Do you think it's possible? Would you know how to implement such a feature?

**Comment by nukeproof** [comment]
Hi allesklar,

The API allows open orders to be filtered by instrument or order id. If you need to filter further, you'll have to retrieve all orders, say for a given instrument, and write your own filter.

For example,

```ruby
client = OandaAPI::Client::TokenClient.new(:practice, ENV.fetch("OANDA_PRACTICE_TOKEN"))

orders = client.account(ENV.fetch("OANDA_PRACTICE_ACCOUNT_NO")).orders(instrument:"EUR_USD").get

filtered_orders = orders.select |order|
  order.type == "limit" && order.price == 1.0650
end
```

These methods might help you implement a more general filter:

```ruby
def account_no
  ENV.fetch "OANDA_PRACTICE_ACCOUNT_NO"
end

def client
  OandaAPI::Client::TokenClient.new :practice, ENV.fetch("OANDA_PRACTICE_TOKEN")
end

def orders(instrument)
  orders = client.account(account_no).orders(instrument: instrument).get
end

def filter_orders(orders, criteria={})
  criteria ? orders.select { |order| criteria.all? { |k, v| order.send(k) == v } } : orders
end

# Returns an array of open buy limit orders, with a price of 1.0650
filtered_orders = filter_orders orders("EUR_USD"), type: "limit", side: "buy", price: 1.0650
```

**Comment by allesklar** [comment]
Very good nukeproof.

I appreciate you taking the time to showing me this. :-)
