### ISSUE TITLE
Invalid JSON Exception

### ISSUE THREAD

**Issue by lifeBCE** [nukeproof/oanda_api#2]
Been using this gem for a few weeks now and have recently implemented the streaming price feed. I periodically get the following error in my logs.

```
#<JSON::ParserError: 757: unexpected token at '{"tick":{"instrument":"AUD_USD","time":"2015-05-06T12:15:00.689991Z","bid":0.8'>
```

I can't tell yet if the issue is within this gem or coming from Oanda themselves. Here is the line of code that triggers the exception.

https://github.com/nukeproof/oanda_api/blob/master/lib/oanda_api/streaming/request.rb#L118

The only thing I can see is maybe the split above this line on line 117 where it splits on \r\n. Obviously this does not happen with every tick so I can only assume that sometimes Oanda may send without that line termination and the split does not properly create the 'json' block variable properly?

**Comment by nukeproof** [comment]
You're right, the code is assuming that each JSON object in the stream is separated with `\r\n` and I guess the tick stream from Oanda is missing that occasionally. The splitting on `\r\n` is a bit hacky on line 117. It should probably use a proper streaming JSON parser like [yajl-ruby](https://github.com/brianmario/yajl-ruby) to handle this instead.  Let me see what I can do.

**Comment by nukeproof** [comment]
v0.9.2 should fix this issue.
