### ISSUE TITLE
Upgrade to v2 REST API?

### ISSUE THREAD

**Issue by mikejarema** [nukeproof/oanda_api#24]
This gem currently appears to use OANDA's v1 REST API:
https://github.com/nukeproof/oanda_api/blob/75ed9afd663f9c4299c13eec644b00a56566885b/lib/oanda_api/configuration.rb#L12

OANDA advises that their v1 REST API is deprecated, and may cease responding by May 2018:
http://developer.oanda.com/rest-live/introduction/ (see banner)

I'm creating this issue to inquire if there any current efforts/plans to adapt the gem for v2, or to update the README if the gem *just works™* by setting `rest_api_version = "v2"`.

**Comment by nukeproof** [comment]
Yeah, that’s unfortunate that the v1 api will be shut down so soon. The current version of oanda_api only supports v1 of the REST api. I haven’t yet started support for v2. When I last looked at Oanda’s v2 schema, I saw endpoints that return many types nested resources and many specialized endpoints. My initial impression was that the current design of oanda_api gem would need to be changed quite a bit to support it.

I’ll take another look at it and update here in about a week as to whether I will go ahead with a v2 version.

**Comment by nukeproof** [comment]
In light of the fact that the v1 API will shutdown shortly, and that the v2 API differs significantly, I’ve decided to sunset this gem. Thanks to everyone who’s contributed over the past few years.

I may decide to release a v2 API ruby gem in the future.

**Comment by allesklar** [comment]
That's too bad. In any case, thanks for your good work nukeproof.

I'm loving this gem.
