### ISSUE TITLE
client.instruments.get : Missing required argument: accountId

### ISSUE THREAD

**Issue by moortimis** [nukeproof/oanda_api#7]
Hi there, the following code returns "Missing required argument: accountId" and despite including account_id and accountId was options in the get method I don't seem to be able to get this to work. 

It looks as if the account_id is required when querying a list of instruments, not sure if its a limitation of the gem or I've just mis understood the documentation. 

--[SAMPLE]
require 'oanda_api'

client = OandaAPI::Client::TokenClient.new(:practice, "<API_TOKEN>")
instruments = client.instruments.get

puts instruments.inspect

--[ERROR]
~/.gem/ruby/gems/oanda_api-0.9.3/lib/oanda_api/client/client.rb:92:in `rescue in execute_request': An error as occured while processing response. Status 400 (OandaAPI::RequestError)
{
	"code" : 2,
	"message" : "Missing required argument: accountId",
	"moreInfo" : "http:\/\/developer.oanda.com\/docs\/v1\/troubleshooting\/#errors"
}
	from ~/.gem/ruby/gems/oanda_api-0.9.3/lib/oanda_api/client/client.rb:78:in `execute_request'
	from ~/.gem/ruby/gems/oanda_api-0.9.3/lib/oanda_api/client/namespace_proxy.rb:107:in `method_missing'
	from oanda_instruments.rb:6:in `<main>'

Thanks

**Comment by nukeproof** [comment]
You're right the documentation is misleading. I'll update it to make it clearer that your need to include an `accountId` parameter when using a practice account. Whether or not you need to include an `accountId` parameter depends on the type of client that you connect to the API. The Oanda [Rates endpoint documentation](http://developer.oanda.com/rest-live/rates/), specifies that an `accountId` parameter is required, however, when connecting with a sandbox client it's not required.

When using a practice account, you should be getting an instruments list like this:

````ruby
client = OandaAPI::Client::TokenClient.new(:practice, ENV.fetch("OANDA_PRACTICE_TOKEN"))
instruments = client.instruments(account_id: 1234).get
````

**Comment by moortimis** [comment]
Thanks for the quick reply, works perfectly.

**Comment by nukeproof** [comment]
:+1:
