### ISSUE TITLE
Persistent connections close unexpectedly when multi-threaded

### ISSUE THREAD

**Issue by nukeproof** [nukeproof/oanda_api#9]
When multiple threads access a single client instance, multiple connections can be created in the persistent_http connection pool. Some conditions seem to cause the tcp sockets in those pooled connections to close. This in turn, can trigger Oanda's 2 connections per second limit to be exceeded, when those connections with closed sockets are attempted to be reused.

Should also confirm whether accessing a single client instance from multiple threads should be supported (eg. is the library and all of its dependancies thread safe?)

**Comment by lifeBCE** [comment]
If you are seeing this in a practice account I believe it is erroneous. It is the 15 requests per second error that is being tripped but they seem to have the wrong error message being presented. Switch your logic to point at sandbox and you will see the correct error.

**Comment by nukeproof** [comment]
Thanks. I came to the same conclusion as well. Have you logged this as an issue with Oanda yet?

**Comment by nukeproof** [comment]
Btw. This [code example](https://gist.github.com/nukeproof/0ab679e4fb997f2f19fb) shows how one could use a single client instance by multiple threads. As I've mentioned in the example's inline comments, a  client instance is inherently not safe for multi-threaded access because it's stateful.

**Comment by lifeBCE** [comment]
I don't think that I agree. I don't know why you say the client is stateful and therefore not thread-safe.

Your example code forces all threads into a waiting line to send their request and wait for the response before allowing another thread to send their request. This does not support throttling at all because if the Oanda API is fast enough, you can still violate the request rate. Furthermore, Oanda can handle multiple simultaneous requests and so can the client instance.

Your throttle logic at the moment piles up numerous threads in a sleep state when they are requesting too fast but then releases them all near the same time causing the same issue again.

**Comment by nukeproof** [comment]
The client is stateful because httparty was not written to be multi-threaded. It keeps track of all of the options that a request uses (headers, connection_adapter, response parser, everything basically) in a hash. In an app that shares a single instance of oanda_api with multiple threads, we can never be sure when the thread scheduler will suspend a thread and wake another. So, if thread A sets some options in the hash, suspends, then thread B wakes to carry on with a request, thread B may have had options set by thread A that it doesn't want.

**Comment by nukeproof** [comment]
I think the true solution is to rewrite the client to use a different http client. I've been thinking of switching to an adapter API like [httpi](http://httpirb.com/) or [faraday](https://github.com/lostisland/faraday). Then, if you wanted your app to support asynchronous http requests, you just use an adapter that supports async requests like [HTTPClient](https://github.com/nahi/httpclient).

**Comment by lifeBCE** [comment]
I see what you are saying and I agree. Yes, any multi-threaded application that shares a single instance of anything should not be modifying that instance unless all other threads have been programmed to detect the change and adjust accordingly and anything that any single thread could set would be valid for all threads. This really has nothing to do with the thread scheduler as that is only one source of a race condition.

I guess my question would be, does this apply? Should this be a concern? This isn't happening and you have control over that at this level. I would imagine that if a user went through all the trouble to have their threads dig down into HTTParty configuration via the `oanda_api` instance and modify it that they would be led to their mistake rather quickly if they did not also take care of what I said above about making the threads smart enough to detect the change.

My long-winded point being, I feel comfortable assuming that the user knows that all threads that share a single instance should work with the parameters of that instance. If new parameters are required, so should be a new instance. :-)
